import { spawnSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, readdirSync, unlinkSync } from "node:fs";
import { createHash } from "node:crypto";
import { homedir } from "node:os";
const result = spawnSync(process.env.CARGO || `${homedir()}/.cargo/bin/cargo`, ["build", "--manifest-path", "engine/Cargo.toml", "--target", "wasm32-unknown-unknown", "--release", "--locked"], { stdio: "inherit" });
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status || 1);
mkdirSync("public/wasm", { recursive: true });
copyFileSync("engine/target/wasm32-unknown-unknown/release/rgb_life.wasm", "public/wasm/rgb_life.wasm");

const bytes=readFileSync("public/wasm/rgb_life.wasm");
const digest=createHash("sha256").update(bytes).digest("hex").slice(0,16);
for(const name of readdirSync("public/wasm")) if(/^rgb_life\.[a-f0-9]{16}\.wasm$/.test(name)) unlinkSync(`public/wasm/${name}`);
const name=`rgb_life.${digest}.wasm`;
copyFileSync("public/wasm/rgb_life.wasm",`public/wasm/${name}`);
mkdirSync("lib",{recursive:true});
writeFileSync("lib/wasm-asset.ts",`// Generated by build-wasm.mjs.\nexport const WASM_PATH = ${JSON.stringify(`/wasm/${name}`)};\n`);
